language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - 'stable'
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
before_script:
  - npm run flow -- check
  - npm run lint
after_success:
  - npm run coverage
